Class cysnet.clinicaDental.agenda.msg.AdmisionResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="AdmisionResponseDefaultData">
<Subscript>"AdmisionResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>AdmisionResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
