Class cysnet.clinicaDental.agenda.msg.BajaPacienteResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="BajaPacienteResponseDefaultData">
<Subscript>"BajaPacienteResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>BajaPacienteResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
