Class cysnet.clinicaDental.agenda.msg.CancelarCitaResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="CancelarCitaResponseDefaultData">
<Subscript>"CancelarCitaResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>CancelarCitaResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
