Class cysnet.clinicaDental.agenda.msg.ModificarCitaResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="ModificarCitaResponseDefaultData">
<Subscript>"ModificarCitaResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>ModificarCitaResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
