Class cysnet.clinicaDental.agenda.msg.NuevoPacienteResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="NuevoPacienteResponseDefaultData">
<Subscript>"NuevoPacienteResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>NuevoPacienteResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
