Class cysnet.clinicaDental.agenda.msg.NuevaNotificacionResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="NuevaNotificacionResponseDefaultData">
<Subscript>"NuevaNotificacionResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>NuevaNotificacionResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
