Class cysnet.clinicaDental.agenda.msg.NuevaAdmisionResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="NuevaAdmisionResponseDefaultData">
<Subscript>"NuevaAdmisionResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>NuevaAdmisionResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
