Class cysnet.clinicaDental.agenda.msg.NuevaAltaResponse Extends (Ens.Response, cysnet.clinicaDental.agenda.msg.GenericResponse)
{

Storage Default
{
<Data name="NuevaAltaResponseDefaultData">
<Subscript>"NuevaAltaResponse"</Subscript>
<Value name="1">
<Value>mensaje</Value>
</Value>
<Value name="2">
<Value>exito</Value>
</Value>
</Data>
<DefaultData>NuevaAltaResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
