version: '3.6'
services:
  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    command: 
      - --default-authentication-plugin=mysql_native_password
    volumes:
    - type: bind
      source: ./mysql-shared
      target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'iris'
      MYSQL_USER: 'iris'
      MYSQL_PASSWORD: 'iris'
      MYSQL_ROOT_PASSWORD: 'iris'
  iris:
    image: containers.intersystems.com/intersystems/irishealth-community-arm64:latest-cd
    #image: containers.intersystems.com/intersystems/irishealth-community:latest-cd
    hostname: katas-iris
    container_name: katas-iris
    restart: always
    ports: 
      - 52773:52773
      - 1972:1972
      - 1980:1980
      - 1981:1981
      - 1982:1982
      - 1983:1983
      - 1984:1984
    command: 
      - --check-caps false
      - --password-file /shared/pass.txt
    volumes: 
      - type: bind
        source: ./iris-shared
        target: /shared
    environment:
      - ISC_DATA_DIRECTORY=/shared/iris