/// Creado desde: http://localhost:52773/csp/healthshare/BOOTCAMP-ENERO-2024/cysnet.miguel.ws.MiServicio.cls?WSDL
Class cysnet.miguel.ws.MiServicio.s0.EnsMessagebody Extends (%SerialObject, %XML.Adaptor) [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "BOOTCAMP-ENERO-2024";

Parameter XMLNAME = "Ens_Messagebody";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "Ens_Messagebody";

Storage Default
{
<StreamLocation>^cysnet.migu34ED.EnsMessagebodyS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
