/// Creado desde: http://localhost:52773/csp/healthshare/BOOTCAMP-ENERO-2024/cysnet.miguel.ws.MiServicio.cls?WSDL
Class cysnet.miguel.ws.MiServicio.s0.EnsResponse Extends cysnet.miguel.ws.MiServicio.s0.EnsMessagebody [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "BOOTCAMP-ENERO-2024";

Parameter XMLNAME = "Ens_Response";

Parameter XMLTYPE = "Ens_Response";

Storage Default
{
<Type>%Storage.Serial</Type>
}

}
